# file: .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug report
description: Report a reproducible problem with arxds
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug! Please include enough detail to reproduce.
  - type: input
    id: version
    attributes:
      label: arxds version
      placeholder: "e.g., 0.1.0"
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "e.g., 3.11.9"
  - type: dropdown
    id: os
    attributes:
      label: OS
      options: [Windows, macOS, Linux]
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact commands, flags, and minimal input
      placeholder: |
        1. ...
        2. ...
        3. ...
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      render: shell
