# file: .github/workflows/release.yml
name: release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Publish (PyPI Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
